apiVersion: console.openshift.io/v1
kind: ConsoleCLIDownload
metadata:
  name: netobserv
  annotations:
    include.release.openshift.io/hypershift: "true"
    include.release.openshift.io/ibm-cloud-managed: "true"
    include.release.openshift.io/self-managed-high-availability: "true"
    include.release.openshift.io/single-node-developer: "true"
    capability.openshift.io/name: Console
spec:
  description: |
    The Network Observability CLI (oc netobserv) provides a lightweight way to quickly debug and troubleshoot network.
    It is deployed separately from the Network Observability Operator.
  displayName: netobserv - Network Observability CLI
  links:
    - href: 'https://mirror.openshift.com/pub/cgw/netobserv/latest/'
      text: Download Network Observability
